### ISSUE TITLE
trying it out....

### ISSUE THREAD

**Issue by devcurmudgeon** [CodethinkLabs/software-dependency-visualizer#1]
On MacOS I had to

```
brew install python3
sudo python3 -m pip install pyyaml neo4jrestclient bottle
After that when I ran the server i got...
```

and the error:

```
~/Projects/2016/software-dependency-visualizer>python3 ./server.py 
Traceback (most recent call last):
File "./server.py", line 50, in 
database = neo4jrestclient.client.GraphDatabase(args.neo4j)
File "/usr/local/lib/python3.5/site-packages/neo4jrestclient/client.py", line 79, in init
response = Request(**self._auth).get(self.url)
File "/usr/local/lib/python3.5/site-packages/neo4jrestclient/request.py", line 63, in get
return self._request('GET', url, headers=headers)
File "/usr/local/lib/python3.5/site-packages/neo4jrestclient/request.py", line 200, in _request
raise StatusException(401, "Authorization Required")
neo4jrestclient.exceptions.StatusException: Code [401]: Unauthorized. No permission -- see authorization schemes.
Authorization Required
```

**Comment by palvarez89** [comment]
Have you configured `neo4j` password? server.py has a hardcoded one by default, you might have to change that...

If you haven't configured the password, I think you can go to http://localhost:7474/ once you have `neo4j` running.

**Comment by devcurmudgeon** [comment]
OK, I got it running, and have submitted a PR. Thanks!
